# Generated by Django 5.0.4 on 2024-08-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='time_payed',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_payed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
