# Generated by Django 5.0.4 on 2024-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_cart_time_payed_alter_cart_date_payed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
